services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: ash
      POSTGRES_DB: adm_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./resources/database_backup.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-express
    working_dir: /backend
    ports:
      - "3250:3250"
    environment:
      - NODE_ENV=development
      - PORT=3250
      - DB_HOST=db
      - DB=adm_test
      - DB_USR=ash
      - DB_PWD=root
      - DB_PORT=5432
      - SECRET_KEY=superSecretKey
      - ALLOWED_USER=apiUsr
      - ALLOWED_PWD=apiPwd
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: node-nextjs
    working_dir: /frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_PUBLIC_BACKEND_API_URL=http://backend:3250
      - NEXT_PUBLIC_BACKEND_USR=apiUsr
      - NEXT_PUBLIC_BACKEND_PWD=apiPwd
    depends_on:
      - backend
volumes:
  postgres-data:
    driver: local
