{{ if eq .Values.type "OKE" }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  gateways:
  - istio-gateway/gateway
  hosts:
  - {{ .Values.ingress.domain }}
  http:
  - route:
    - destination:
        host:  {{ include "helm.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{ end }}